apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d76p8d9sa-go
  janus-idp.io/tekton: d76p8d9sa-go
  backstage.io/kubernetes-id: d76p8d9sa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d76p8d9sa-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
